### PR TITLE
Use collate_fn to skip corrupt images without using recursion

### PR DESCRIPTION
**Pull request by afiaka87**
I've tested this on a particularly annoying version of Wikiart with captions I have that has many corrupt images. Works well. 
Screenshot from 2021-12-03 19-28-48

### CODE REVIEW

**Comment by afiaka87** [comment]
> clip_retrieval/clip_inference.py:90:16: W0702: No exception type(s) specified (bare-except)

I love CI. Give me a moment to patch this.

**Comment by rom1504** [comment]
Thanks, that looks pretty good 
Can you run `make black` to fix the formatting ?
(You can install it with make install-dev)

**Comment by afiaka87** [comment]
@rom1504 Sure thing. Apologies, should have read the readme.

**Comment by afiaka87** [comment]
@rom1504 Okay should be good to go.

**Comment by rom1504** [comment]
Thanks

**Comment by heyalexchoi** [comment]
looks like this feature was removed
@rom1504 any recommendations for handling potentially corrupt / empty files? should we do our own preprocessing to check the validity of the images?
`PIL.UnidentifiedImageError: cannot identify image file `

**Comment by rom1504** [comment]
No not sure why that was removed.

Let's add it back there https://github.com/rom1504/clip-retrieval/blob/main/clip_retrieval/clip_inference/reader.py#L97

**Comment by heyalexchoi** [comment]
@rom1504 
https://github.com/rom1504/clip-retrieval/pull/330

**Pull request merged**
