### PR TITLE
responsive styling for front

### PR DESCRIPTION
**Pull request by rvencu**
improve the visuals on all devices

### CODE REVIEW

**Comment by rom1504** [comment]
Screenshot_20210913_221926

on mobile that puts the results very low

I don't think that's better than the current thing:

Screenshot_20210913_222158

**Comment by rom1504** [comment]
Screenshot_20210913_222657

Also there's too much space between the left pane and the right pane on large resolution

not really a fan of the font also, I think it's a bit harder to read

**Comment by rom1504** [comment]
for the test, just run npm run fix

**Comment by rvencu** [comment]
on mobile we can reverse and put the sidebar at the bottom not on the top
font, easy to replace with any google font or revert to basic fonts
on desktop - white space is important maybe not in excess but compared to the original some is needed as opposed to none

**Comment by rvencu** [comment]
I got your changes and also finished my styling proposal to the point I am happy with. Please review

**Comment by rom1504** [comment]
did you try several resolutions ? you can check that with chrome dev tools
Some examples of what I'm seeing:

high rez
Screenshot_20210915_215111
why such an empty space on the left ?

Why is image written next to the search bar ?

low rez
Screenshot_20210915_215306

information and controls are now completely at the bottom, completely hidden

the other resolutions work reasonably well

**Comment by rvencu** [comment]
the empty space on left can still be improved if you feel the need for pixel perfect css. For resolutions higher than 1920px horizontally the entire thing stays centered on the page. It does not feel such imbalanced if I keep the sidebar aligned to right and close to results (as you complained with big space between sidebar and content)

also, controls at the bottom are opposed to controls at the top. they need to be one or another on mobile so please choose what you like best. As the initial screen is empty, controls are very visible and the user become aware they exist. I would prefer them on top as I proposed first time

**Comment by rom1504** [comment]
Basically I'm ok to merge something that is better than the current thing in all resolutions from high to low. Currently it's good for medium, but worse for high and low. Better is defined in term of usability in priority and of UI secondary.

Why not use the whole space in high resolutions ?

" they need to be one or another on mobile ", no they don't, they can be on the side as the current setup. It's not pretty but it works, whereas if you put them on the top or the bottom, it doesn't work, on the top the user doesn't see the results, on the bottom he doesn't see the controls. It's not only about being aware, it's also about minimizing the time to scroll

"I just put text and image labels to the controls so the user have an idea what is that"
I think the icons are intuitive. It's what other platforms do, I don't think we need the label

If you want to improve things, I'd suggest taking as example an existing app, like google shopping / google images or some other search engine UX

**Comment by rvencu** [comment]
ok, I'll play more with it along these lines but UX is not something I really like much to work on. just wanted to minimize your time on that

**Comment by rom1504** [comment]
Yeah it's ok

What are the main changes you'd like to have done with this PR ?

It's up to you to work on it or not
In my opinion the current state is usable
It could be made more pretty and more usable on some devices maybe but it would be ok to keep it just like that I think

**Comment by rvencu** [comment]
got it closer to your opinion I hope...

**Comment by rom1504** [comment]
on mobile there is still only one column, it seems to me 3 columns is better (with smaller images)
on desktop the left column is still a bit too large on high resolution, and the font is a bit larger than before

sorry to repeat, but I don't really understand the objective of this PR
What is the improvement goal?

**Comment by rvencu** [comment]
Well I do not need the PR. I was under impression that you asked me to suggest styling improvements and it was easier for me to show instead of explain. If I understood wrongfully then just discard it. Thanks

**Comment by rom1504** [comment]
ok let's just keep the current thing for now

**Pull request closed without merging**
