### PR TITLE
Add support for the full open clip model name format : ViT-B-32/laion2b_s34b_b79k

### PR DESCRIPTION
**Pull request by mehdidc**
This leaves the defaults the same, but allow the possibility to specify a checkpoint if needed (i.e, corresponds to the `pretrained` parameter of open clip).

### CODE REVIEW

**Comment by mehdidc** [comment]
I think, ideally there should be a dict mapping each model to the best available checkpoint (e.g., according to imagenet zero-shot classification results)

**Comment by heyalexchoi** [comment]
this would be nice. took awhile for me to figure out which open clip checkpoint actually made my embedding, and it seems the default for 'ViT-L-14' scored considerably lower than some of the other options.

**Comment by rom1504** [comment]
this looks similar in intent to #284 but there is no doc nor test

**Comment by rom1504** [comment]
I changed this to be like ViT-B-32/laion2b_s34b_b79k with no new arg clip checkpoint

that makes it cleaner imo and does not leak the openclip interface in the top level interface of clip retrieval

it allows for other clip model interfaces to have different model formats

**Pull request merged**
