### PR TITLE
Update Clip Back section of README

### PR DESCRIPTION
**Pull request by varadgunjal**
- Added details to help users who will use the LAION-5B index from HuggingFace

### CODE REVIEW

**Comment by rom1504** [comment]
could you instead make a dedicated .md for laion5B index with step by step instructions?

**Comment by varadgunjal** [comment]
Sure I'll do that.

**Comment by rom1504** [comment]
can you please tell me if that works for you https://github.com/rom1504/clip-retrieval/blob/ee0de465c098321c41c71f8843283b99f0b8928f/docs/laion5B_back.md ?

**Comment by varadgunjal** [comment]
@rom1504 Sorry I missed this. Yes, I can confirm this works for me.

**Comment by rom1504** [comment]
alright let's go with that then

**Pull request closed without merging**
