### PR TITLE
Integration with hugging face ClipModel #26

### PR DESCRIPTION
**Pull request by Sofianel5**
Allows usage of huggingface ClipModel backends such as https://huggingface.co/patrickjohncyh/fashion-clip or https://huggingface.co/laion/CLIP-ViT-L-14-DataComp.XL-s13B-b90K.
Also minor changes such as creating 4 dataloader workers instead of 8 to avoid performance issues.

### CODE REVIEW

**Comment by rom1504** [comment]
hi, could you please fix the CI ?

**Comment by rom1504** [comment]
can you add a test for it at https://github.com/rom1504/clip-retrieval/blob/main/tests/test_clip_inference/test_mapper.py ?

**Comment by Sofianel5** [comment]
Hey is anything still blocking merge?

**Comment by mehdidc** [comment]
Would be great to have this, can we merge @rom1504 ?

**Comment by rom1504** [comment]
sorry for the delay, and thank you for the PR!

**Pull request merged**
